name: Django CI/CD Workflow

on:
  push:
    branches:
      - develop
      - main  # Allows deployment only on main branch

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0  # Stable version of Python supported by GitHub Actions

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Snyk Vulnerability Scan
      if: github.ref == 'refs/heads/develop'  # Run only for develop branch
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: SonarQube Analysis
      if: github.ref == 'refs/heads/develop'  # Run only for develop branch
      run: |
        sonar-scanner \
          -Dsonar.projectKey=django-task-manager \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

    - name: Run Tests
      run: python manage.py test

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
