name: Django CI/CD with DevSecOps

on:
  push:
    branches:
      - develop
      - main

jobs:
  test-and-security:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: task_manager_db
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        python manage.py test

    - name: Run Snyk Vulnerability Scan
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        pip install snyk
        snyk auth $SNYK_TOKEN
        snyk test

    - name: Dependency Security Scan (Safety)
      run: |
        pip install safety
        safety check -r requirements.txt

    - name: Static Code Analysis (SonarQube)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my-project \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

    - name: Dynamic Security Test (OWASP ZAP)
      uses: zapbot/action-zap@v1
      with:
        cmd: zap-baseline.py -t http://localhost:8000

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        aws ecs update-service --cluster your-cluster-name \
          --service your-service-name --force-new-deployment
